version: '3'
networks:
  laravel:

services:
  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src/app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    restart: unless-stopped
    networks:
      - laravel
  #MYSQL service
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  #PHP Service
  php:
    build:
      context: .
      dockerfile: DockerFile
    container_name: php
    volumes:
      - ./src/app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel